name: Deploy Live Project to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@latest

      - name: Setup Pages
        uses: actions/configure-pages@latest

      - name: Upload Live Project folder
        uses: actions/upload-pages-artifact@latest
        with:
          path: 'Live Project'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@latest
